
import json
import logging
from typing import Any

import GEOparse
import ollama
from pydantic import BaseModel, Field

from de_pipeline import (
    annotate_ensembl_ids,
    build_expression_matrix,
    fetch_geo_data,
    filter_deg_results,
    run_deseq2_analysis,
)
from tools import DESEQ2_TOOL_SCHEMA, INSPECT_METADATA_SCHEMA

logging.basicConfig(level=logging.INFO)

class ActionDecision(BaseModel):
    tool_name: str = Field(
        description="Must be either 'inspect_geo_metadata' or 'run_full_deseq2_pipeline'"
    )
    geo_id: str = Field(description="The GEO accesion ID, e.g., 'GSE159034'")
    condition_col: str | None = Field(
        default = None,
        description="The metadata column name, or null if unknown",
    )
    test_group: str | None = Field(
        default=None, description="Test group (e.g. Responder) or null"
    )
    reference_group: str | None = Field(
        default=None, description="Control group (e.g. Non-responder) or null"
    )

def run_agent_query(user_query: str, model_name: str = "qwen2.5:32b") -> dict[str, Any]:
    logging.info(f"User Query: {user_query}")

    messages = [
        {
            "role": "system",
            "content": (
                "You are a bioinformatics assistant. If you lack exact metadata columns names "
                "to run an analysis, invole 'inspect_geo_metadata' forst to inspect available columns."
            ),
        },
        {
            "role": "user",
            "content": user_query
        },
    ]
    tools = [INSPECT_METADATA_SCHEMA, DESEQ2_TOOL_SCHEMA]

    while True:
        # Prompt local LLM along with registered tool schemas
        response = ollama.chat(
            model=model_name,
            messages=messages,
            tools=tools,
        )
        msg = response["message"]
        messages.append(msg)

        # Extract tool calls generated by the LLM
        tool_calls = msg.get("tool_calls", [])

        if not tool_calls:
            print("Model did not generate a tool call:")
            print(response["message"].get("content", "No response content."))
            return {}

        # Process and execute the requested tool call
        for tool_call in tool_calls:
            func_name = tool_call["function"]["name"]
            func_args = tool_call["function"]["arguments"]

            if func_name in TOOL_MAP:
                logging.info(
                    f"Model invoked '{func_name}' with arguments: {func_args}"
                )

                # Execute Python tool function
                tool_output = TOOL_MAP[func_name](**func_args)

                # Feed tool execution output back to LLM context
                messages.append(
                    {
                        "role": "tool",
                        "content": json.dumps(tool_output),
                    }
                )

                # If the pipeline finished, return the result dict
                if func_name == "run_full_deseq2_pipeline":
                    return tool_output

def run_agent_with_forced_json(user_query: str, model_name: str = "qwen2.5:32b"):
    messages=[
        {
            "role": "system",
            "content": (
                "Select the appropriate tool and extract arguments. "
                "If you do not know the exact condition column name, select 'inspect_geo_metadata'."
            ),
        },
        {"role": "user", "content": user_query},
    ]

    while True:
        response = ollama.chat(
            model=model_name,
            messages=messages,
            format=ActionDecision.model_json_schema(),
        )

        content = response["message"]["content"]
        action = ActionDecision.model_validate_json(content)

        if action.tool_name == "inspect_geo_metadata":
            output = inspect_geo_metdata(geo_id=action.geo_id)
            messages.append({"role": "assistant", "content": content})
            messages.append(
                {
                    "role": "user",
                    "content": f"Metadata inspection results: {json.dumps(output)}. Now select 'run_full_deseq2_pipeline' with the exact condition_col."
                }
            )

        elif action.tool_name == "run_full_deseq2_pipeline":
            return execute_deseq2_pipeline(
                geo_id=action.geo_id,
                condition_col=action.condition_col,
                test_group=action.test_group,
                reference_group=action.reference_group,
            )

def inspect_geo_metadata(geo_id: str) -> dict[str, Any]:
    logging.info(f"AGENT TOOL TRIGGERED: Inspecting metadata for {geo_id}")

    # Fetch metadata only (no supp files)
    dataset_dir = f"./raw_data/{geo_id}"
    gse = GEOparse.get_GEO(geo=geo_id, destdir=dataset_dir)
    df = gse.phenotype_data

    # Find cols that have between 2 and 10 unique categorical values (filtering out high-cardinality metdata like individual patient IDs)
    candidate_columns = {}
    for col in df.columns:
        unique_vals = df[col].dropna().unique().tolist()
        if 1 < len(unique_vals) <= 10:
            candidate_columns[col] = unique_vals

    return {"geo_id": geo_id, "potential_condition_columns": candidate_columns}

def execute_deseq2_pipeline(
    geo_id: str,
    condition_col: str,
    test_group: str,
    reference_group: str,
    padj: float = 0.05,
    lfc: float = 1.0,
) -> dict[str, Any]:

    logging.info(f"AGENT TOOL TRIGGERED: Analyzing {geo_id} ({test_group} vs {reference_group})")

    contrast = [condition_col, test_group, reference_group]

    # Fetch raw GEO and supp folder path
    gse, supp_dir = fetch_geo_data(geo_id=geo_id)

    # Build the count matrix from supp files
    counts_df = build_expression_matrix(supp_dir=supp_dir)

    # Run PyDeseq2
    raw_results = run_deseq2_analysis(
        counts_df=counts_df,
        phenotype_df=gse.phenotype_data,
        condition_col=condition_col,
        contrast=contrast,
    )

    # Map Ensembl IDs to gene symbols
    annotated_results = annotate_ensembl_ids(raw_results)

    # Filter top DEGs based on thresholds
    upregulated, downregulated = filter_deg_results(annotated_results, padj_thresh=padj, lfc_thresh=lfc)

    # Package execution summary to return to the agent framework
    return {
        "status": "success",
        "geo_id": geo_id,
        "total_upregulated": len(upregulated),
        "total_downregulated": len(downregulated),
        "top_upregulated_genes": upregulated.index[:10].tolist(),
        "top_downregulated_genes": downregulated.index[:10].tolist(),
    }

TOOL_MAP = {
    "inspect_geo_metadata": inspect_geo_metadata,
    "run_full_deseq2_pipeline": execute_deseq2_pipeline,
}

if __name__ == "__main__":
    query = (
        "Run DESeq2 on GSE159034 comparing 'Responder' vs 'Non-responder' "
        "using 'characteristics_ch1.1.primary response' as the condition."
    )

    result = run_agent_query(query)
    print("\nFinal Result:\n", json.dumps(result, indent=2))
