
import pandas as pd
import json
import logging
from typing import Any

import GEOparse
import ollama
import mygene
from pydantic import BaseModel, Field

from de_pipeline import analyze_and_save

from tools import DESEQ2_TOOL_SCHEMA, INSPECT_METADATA_SCHEMA, GENE_LOOKUP_SCHEMA

logging.basicConfig(level=logging.INFO)

class ActionDecision(BaseModel):
    tool_name: str = Field(
        description="Must be either 'inspect_geo_metadata' or 'run_full_deseq2_pipeline'"
    )
    geo_id: str = Field(description="The GEO accesion ID, e.g., 'GSE159034'")
    condition_col: str | None = Field(
        default = None,
        description="The metadata column name, or null if unknown",
    )
    test_group: str | None = Field(
        default=None, description="Test group (e.g. Responder) or null"
    )
    reference_group: str | None = Field(
        default=None, description="Control group (e.g. Non-responder) or null"
    )

def run_agent_query(user_query: str, model_name: str = "qwen2.5:32b") -> dict[str, Any]:
    logging.info(f"User Query: {user_query}")

    messages = [
        {
            "role": "system",
            "content": (
                "You are a bioinformatics assistant. If you lack exact metadata columns names "
                "to run an analysis, invoke 'inspect_geo_metadata' forst to inspect available columns."
            ),
        },
        {
            "role": "user",
            "content": user_query
        },
    ]
    tools = [INSPECT_METADATA_SCHEMA, DESEQ2_TOOL_SCHEMA]

    while True:
        # Prompt local LLM along with registered tool schemas
        response = ollama.chat(
            model=model_name,
            messages=messages,
            tools=tools,
        )
        msg = response["message"]
        messages.append(msg)

        # Extract tool calls generated by the LLM
        tool_calls = msg.get("tool_calls", [])

        if not tool_calls:
            print("Model did not generate a tool call:")
            print(response["message"].get("content", "No response content."))
            return {}

        # Process and execute the requested tool call
        for tool_call in tool_calls:
            func_name = tool_call["function"]["name"]
            func_args = tool_call["function"]["arguments"]

            if func_name in TOOL_MAP:
                logging.info(
                    f"Model invoked '{func_name}' with arguments: {func_args}"
                )

                # Execute Python tool function
                tool_output = TOOL_MAP[func_name](**func_args)

                # Feed tool execution output back to LLM context
                messages.append(
                    {
                        "role": "tool",
                        "content": json.dumps(tool_output),
                    }
                )

                # If the pipeline finished, return the result dict
                if func_name == "run_full_deseq2_pipeline":
                    return tool_output

def run_agent_with_forced_json(user_query: str, model_name: str = "qwen2.5:32b"):
    messages=[
        {
            "role": "system",
            "content": (
                "Select the appropriate tool and extract arguments. "
                "If you do not know the exact condition column name, select 'inspect_geo_metadata'."
            ),
        },
        {"role": "user", "content": user_query},
    ]

    while True:
        response = ollama.chat(
            model=model_name,
            messages=messages,
            format=ActionDecision.model_json_schema(),
        )

        content = response["message"]["content"]
        action = ActionDecision.model_validate_json(content)

        if action.tool_name == "inspect_geo_metadata":
            output = inspect_geo_metdata(geo_id=action.geo_id)
            messages.append({"role": "assistant", "content": content})
            messages.append(
                {
                    "role": "user",
                    "content": f"Metadata inspection results: {json.dumps(output)}. Now select 'run_full_deseq2_pipeline' with the exact condition_col."
                }
            )

        elif action.tool_name == "run_full_deseq2_pipeline":
            return execute_deseq2_pipeline(
                geo_id=action.geo_id,
                condition_col=action.condition_col,
                test_group=action.test_group,
                reference_group=action.reference_group,
            )

def inspect_geo_metadata(geo_id: str) -> dict[str, Any]:
    logging.info(f"AGENT TOOL TRIGGERED: Inspecting metadata for {geo_id}")

    # Fetch metadata only (no supp files)
    dataset_dir = f"./raw_data/{geo_id}"
    gse = GEOparse.get_GEO(geo=geo_id, destdir=dataset_dir)
    df = gse.phenotype_data

    # Find cols that have between 2 and 10 unique categorical values (filtering out high-cardinality metdata like individual patient IDs)
    candidate_columns = {}
    for col in df.columns:
        unique_vals = df[col].dropna().unique().tolist()
        if 1 < len(unique_vals) <= 10:
            candidate_columns[col] = unique_vals

    return {"geo_id": geo_id, "potential_condition_columns": candidate_columns}

def execute_deseq2_pipeline(
    geo_id: str,
    condition_col: str,
    test_group: str,
    reference_group: str,
    outdir: str = "./results",
    padj: float = 0.05,
    lfc: float = 1.0,
    n_cpus: int = 4,
) -> dict[str, Any]:

    logging.info(f"AGENT TOOL TRIGGERED: Analyzing {geo_id} ({test_group} vs {reference_group})")

    results = analyze_and_save(
        geo_id=geo_id,
        condition_col=condition_col,
        test_group=test_group,
        reference_group=reference_group,
        outdir=outdir,
        padj=padj,
        lfc=lfc,
        n_cpus=n_cpus,
    )

    return results

def lookup_gene_in_results(gene_symbol: str, files: dict[str, str], padj_thresh: float, lfc_thresh: float,) -> dict:
    symbol = gene_symbol.strip()

    hits = mygene.MyGeneInfo().querymany(
        [symbol],
        scopes="symbol",
        fields="symbol,ensembl.gene",
        species="human"
    )

    ensembl_ids = set()

    for hit in hits:
        if str(hit.get("symbol", "")).casefold() != symbol.casefold():
            continue

        ensembl = hit.get("ensembl", [])
        records = ensembl if isinstance(ensembl, list) else [ensembl]

        for record in records:
            if isinstance(record, dict) and record.get("gene"):
                ensembl_ids.add(record["gene"])

    if not ensembl_ids:
        return {"gene_symbol": symbol, "status": "symbol_not_resolved", "matches": []}

    raw = pd.read_csv(files["raw"], index_col=0)

    unversioned_ids = [str(gene_id).split(".", 1)[0] for gene_id in raw.index]
    matching_rows = raw.loc[pd.Index(unversioned_ids).isin(ensembl_ids)]

    matches = []
    for gene_id, row in matching_rows.iterrows():
        fold_change = None if pd.isna(row["log2FoldChange"]) else float(row["log2FoldChange"])
        adjusted_p = None if pd.isna(row["padj"]) else float(row["padj"])
        p_value = None if pd.isna(row["pvalue"]) else float(row["pvalue"])

        passes_cutoffs =(
            adjusted_p < padj_thresh and abs(fold_change) > lfc_thresh
            if adjusted_p is not None and fold_change is not None
            else None
        )
        matches.append({
            "ensembl_id": str(gene_id),
            "log2FoldChange": fold_change,
            "pvalue": p_value,
            "padj": adjusted_p,
            "passes_deg_cutoffs": passes_cutoffs,
        })

    return {
        "gene_symbol": gene_symbol,
        "status": "found" if matches else "not_in_raw_results",
        "matches": matches,
    }

def summarize_analysis(user_prompt, results):
    messages=[
        {
            "role": "system",
            "content": "You are a bioinformatics assistant. Summarize DESeq2 results clearly for scientists.",
        },
        {
            "role": "user",
            "content": (
                f"User request:\n{user_prompt}\n\n"
                f"Analysis results:\n{json.dumps(results)}\n\n"
                "If the user request contains a specific question, answer it using only the supplied results. "
                "Before responding to a request about a named gene, call lookup_gene. "
                "If it is absent from both lists, say it was not found among genes passing the configured cutoffs; do not infer its exact statistics. "
                "If the user request does not contain a specific question, summarize the main results."
            )
        }
    ]

    response = ollama.chat(
        model="qwen2.5:32b",
        messages=messages,
        tools=[GENE_LOOKUP_SCHEMA],
    )

    tool_calls = response["message"].get("tool_calls") or []

    if tool_calls:
        messages.append(response["message"])

        for call in tool_calls:
            function = call["function"]
            if function["name"] != "lookup_gene":
                raise ValueError(f"Unexepected tool: {function['name']}")

            lookup_result = lookup_gene_in_results(
                function["arguments"]["gene_symbol"],
                results["files"],
                padj_thresh=results["padj_threshold"],
                lfc_thresh=results["lfc_threshold"],
            )
            messages.append({
                "role": "tool",
                "tool_name": "lookup_gene",
                "content": json.dumps(lookup_result),
            })

        response = ollama.chat(model="qwen2.5:32b", messages=messages)

    return response["message"]["content"]

TOOL_MAP = {
    "inspect_geo_metadata": inspect_geo_metadata,
    "run_full_deseq2_pipeline": execute_deseq2_pipeline,
}

if __name__ == "__main__":
    query = (
        "Run DESeq2 on GSE159034 comparing 'Responder' vs 'Non-responder' "
        "using 'characteristics_ch1.1.primary response' as the condition."
    )

    result = run_agent_query(query)
    print("\nFinal Result:\n", json.dumps(result, indent=2))
